name: Deploy Storybook

on:
  push:
    branches:
      - main # or master, depending on your default branch name

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for Git history

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: NODE_ENV=production npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static # The folder storybook builds to
          branch: gh-pages # The branch to deploy to
          clean: true # Automatically remove deleted files from the deployment
